source "https://rubygems.org"

gem "rails", "~> 5.0.1"
gem "sqlite3"
gem "puma", "~> 3.0"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.2"
gem "jquery-rails"
gem "turbolinks", "~> 5"
gem "jbuilder", "~> 2.5"
gem "will_paginate"
gem "bootstrap-will_paginate"
gem "bootstrap-sass"

group :development, :test do
  gem "byebug", "9.0.0", platform: :mri
end

group :development do
  gem "web-console", "3.1.1"
  gem "listen", "3.0.8"
  gem "spring", "1.7.2"
  gem "spring-watcher-listen", "2.0.0"
end

group :test do
  gem "rails-controller-testing", "0.1.1"
  gem "minitest-reporters", "1.1.9"
  gem "guard", "2.13.0"
  gem "guard-minitest", "2.4.4"
end

group :production do
  gem "pg", "0.18.4"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
